spring:
  application:
    name: utilisateurs
  datasource:
    url: jdbc:h2:mem:utilisateurs
    username: root
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true # Pour eviter que le script data.sql s'execute avant l'initialisation Hibernate.
    h2:
      console.enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka #le lien vers le serveur eureka

server:
  servlet:
    context-path: /utilisateurs
